#!/usr/bin/env bash
# configure domain zone so that www points to load balancer

if [ "$#" = 1 ]
then
    sub_domains=("www" "lb-01" "web-01" "web-02")
    for sub_domain in "${sub_domains[@]}"
    do
	rt=$(dig $sub_domain.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
        destination=$(dig $sub_domain.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
	echo "The subdomain $sub_domain is a $rt record and points to $destination"
    done
elif [ "$#" = 2 ]
then
    rt=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
    destination=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
    echo "The subdomain $2 is a $rt record and points to $destination"
fi