#!/usr/bin/env bash
#install nginx in server
sudo apt-get update
sudo apt install nginx -y
sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo service nginx restart