#!/usr/bin/env bash
# configure web 02 to web 01

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
chmod -R 755 /var/www/html/
echo 'Hello World' > /var/www/html/index.nginx-debian.html
chmod 666 /var/www/html/
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart