#!/usr/bin/env bash
#install and configure HAproxy on lb-01 server

sudo apt update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend
backend web-backend
        balance roundrobin
        server web1 34.229.63.78 check
        server web2 18.207.236.83 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
