#!/usr/bin/env bash
#Bash script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump -u root -p"$1" --all-databses > backup.sql
dmy=$(date '+%d-%m-%Y')
tar -cvzf "$dmy".tar.gz backup.sql