#!/usr/bin/env bash
#do task 0 making it short and sweet
sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
service nginx restart
kill -9  "$(pgrep 'nginx'|head -1)"
